### ISSUE TITLE
Peer-to-Peer Review

### ISSUE THREAD

**Issue by Drod86** [Xghayor/Portfolio#9]
<h2>Morning Session - 20.6.23
Daniel
- I suggest you remove the inner divs and make this container a flexbox
- Perhaps consider more specific class naming 
```html
<div  class="hr-container">
    <div> <h3  class="hr">My Recent Work</h3></div>
   <div><hr class="works-hr"></div>

  </div
``` 
Gumaro
- consider using adding 'class="container" to <header> rather than extra div child element
```html
<header>
    <div class="container">
      <div class="logo">...
```

**Comment by Xghayor** [comment]
1.Removed inner divs- worked totally fine.
2.changed to flexbox, however it did not work-out so the did not change it.
3.Modified class naming for better understanding
